[tool.poetry]
name = "oz-mini-project"
version = "0.1.0"
description = ""
authors = ["BE02LEEJAEHOON <ljhx6787@naver.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
